name: Update Submodules

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через интерфейс

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "true" # Подтягиваем подмодули

      - name: Update submodules
        run: |
          git submodule update --remote --merge # Обновляем подмодули до последних коммитов

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main # Убедитесь, что вы находитесь на правильной ветке
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Используем токен для аутентификации
