name: Update Submodules
on:
  workflow_dispatch: # Позволяет запускать workflow вручную через интерфейс
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: recursive
      - name: Update module
        run: |
          git submodule update --remote --merge --allow-unrelated-histories
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "deploy: ${{github.event.client_payload.module}} - ${{github.event.client_payload.sha}}"
          git push
